name: Weekly auto test

on:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
      MERCHANT_KEY: ${{ secrets.MERCHANT_KEY }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Run linting
      run: yarn lint
    - name: Run tests
      run: yarn test